/* 
 * gcc dbfunc.c -o dbfunc
 * Database function implementations
 * */

/*

   Copyright [2012] [harshvardhan pandit]

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
   
 */

#include "dbfunc.h"

/* ---------------- ADD/REMOVE -------------------- */

/* addtag: 
 * input: tagname as string
 * return: integer for operation status
 * operation: Create a new tag in kwest
 * */
int addtag(char *tagname)
{
 /* OPERATION
  * int t_hashkey=sethashtag(tagname)
  * Query : Add to TagDetails Table(t_hashkey,tagname)
  * */
 return 0;
}

/* removetag: 
 * input: tagname as string
 * return: integer for operation status
 * operation: Remove an existing tag from kwest
 * */
int removetag(char *tagname)
{
 /* OPERATION
  * int t_hashkey = gethashtagkey(tagname)
  * Query : Check if any entry for the tag exist in FileAssociation table
  * prompt user to deal with existing entries if any
  * Query : remove tag entry from TagDetails Table
  * */
 return 0;
}

/* addfile: 
 * input: abspath (Absolute Path) as string. It is the path of the file in base file system on which fuse is mounted.
 * return: integer for operation status
 * operation: Add file to kwest
 * */
int addfile(char *abspath)
{
 /* OPERATION
  * int f_hashkey=sethashfile(abspath)
  * Get f_name form path
  * Query : Add to FileDetails Table(f_hashkey,f_name,abspath)
  * struct meta m = generatemetadata()	//Function which returns metadata using libraries
  * addfilemetadata(f_hashkey,m)
  * */
 return 0;
}

/* removefile: 
 * input: path as string. path can be a filename or a hierarchy of tags it is associated with in kwest.
 * return: integer for operation status
 * operation: Remove file form kwest
 * */
int removefile(char *path)
{
 /* OPERATION
  * int f_hashkey=gethashfilekey(path)
  * Query : Check if any entry with f_hashkey exist in FileAssociation Table
  * prompt user to deal with existing entries if any
  * removefilemetadata(f_hashkey)
  * Query : remove file entry from FileDetails  Table
  * */
 return 0;
}

/* addfilemetadata: 
 * input: Hash value for file (f_hashkey) as integer
 * input: structure meta. It holds all metadata associated with a file, generated by external libraries.
 * return: integer for operation status
 * operation: Add metadata for a file generated by external libraries
 * */
int addfilemetadata(int f_hashkey,struct meta *m)
{
 /* OPERATION			
  * Query : add meta-info in structure meta to FileMetadata Table for file(f_hashkey)
  * */
 return 0;
}

/* removefilemetadata: 
 * input: Hash value for file (f_hashkey) as integer
 * return: integer for operation status
 * operation: Remove metadata for existing file
 * */
int removefilemetadata(int f_hashkey)
{
 /* OPERATION
  * Query : remove entry of file(f_hashkey) from FileMetadata Table
  * */
 return 0;
}

/* --------------- Tag-File Relation ------------- */

/* tagfile: 
 * input: tagname as string
 * input: filename as string
 * return: integer for operation status
 * operation: Associate a tag with a file
 * */
int tagfile(char *t,char *f)
{
 /* OPERATION
  * int t_hashkey=gethashtagkey(t)
  * int f_hashkey=gethashfilekey(f)
  * Query : check if entry exists in File Association Table
  * Query : add t_hashkey,f_hashkey to File Association Table
  * */
 return 0;
}

/* untagfile: 
 * input: tagname as string
 * input: filename as string
 * return: integer for operation status
 * operation: Remove the existing association between the tag and file
 * */
int untagfile(char *t,char *f)
{
 /* OPERATION
  * int t_hashkey=gethashtagkey(t)
  * int f_hashkey=gethashfilekey(f)
  * Query : remove t_hashkey,f_hashkey from File Association Table
  * */
 return 0;
}

/* getfile: 
 * input: tagname as string
 * return: filename as string. NULL if no file found
 * operation: Return list of files associated to given tag
 * */
char *getfile(char *t)
{
 /* OPERATION
  * int t_hashkey=gethashtagkey(t)
  * Query : get f_hashkey from FileAssociation Table
  * char *f_name = gethashfile(f_hashkey)
  * return f_name
  * */
 return 0;
}

/* gettag: 
 * input: filename as string
 * return: tagname as string. NULL if no tag found.
 * operation: Return list of tags associated with a given file
 * */
char *gettag(char *f)
{
 /* OPERATION
  * int f_hashkey=gethashfilekey(f)
  * Query : get t_hashkey from FileAssociation Table
  * char *tagname = gethashtag(t_hashkey)
  * return tagname
  * */
 return 0;
}


/*----------------- Tag-Tag Relation ------------------*/

/* addassociation: 
 * input: tagname of both tags to be associated as string
 * input: relationtype between tags to be formed as string
 * return: integer for operation status
 * operation: Associate a tag with another tag
 * */
int addassociation(char *t1,char *t2,char *relationtype)
{
 /* OPERATION
  * int relationid=getrelationid(relationtype)
  * int t1=gethashtagkey(t1)
  * int t2=gethashtagkey(t2)
  * Query : check if entry exists in TagAssociation Table
  * Query : add t1, t2,relationid to TagAssociation Table
  * */
 return 0;
}

/* removeassociation: 
 * input: tagname of both tags whose associated is to be removed as string
 * input: relationtype between tags to be removed as string
 * return: integer for operation status
 * operation: Remove the existing association between the two tags
 * */
int removeassociation(char *t1,char *t2,char *relationtype)
{
 /* OPERATION
  * int relationid=getrelationid(relationtype)
  * int t1=gethashtagkey(t1)
  * int t2=gethashtagkey(t2)
  * Query : remove entry t1, t2,relationid from TagAssociation Table
  * */
 return 0;
}

/* getassociationrelation: 
 * input: tagname of both tags in association as string
 * return: relationid between tags as integer
 * operation: Return type of association between the two tags
 * */
int getassociationrelation(char *t1,char *t2)
{
 /* OPERATION
  * int t1=gethashtagkey(t1)
  * int t2=gethashtagkey(t2)
  * Query : return relationid from entry t1, t2 from TagAssociation Table
  * */
 return 0;
}

/* getassociation: 
 * input: tagname as string
 * input: relationtype between tags as string
 * return: related tagname as string
 * operation: Get tag having a particular association with another tag
 * */
char* getassociation(char *t,char *relationtype)
{
 /* OPERATION
  * int relationid=getrelationid(relationtype)
  * int t1=gethashtagkey(t)
  * Query : get t2 from entry t1, relationid from TagAssociation Table
  * char *tag = gethashtag(t2)
  * return tag
  * */
 return 0;
}

/* ----------------- Associations --------------------- */

/* addrelation: 
 * input: relationtype as string
 * return: relationid as integer. 0 if unable to add relation
 * operation: Create a new association type
 * */
int addrelation(char *relationtype)
{
 /* OPERATION
  * Query : check if entry exists in AssociationRelation Table
  * Generate now relationid (increment)
  * Query : add relationid,relationtype to AssociationRelation Table
  * */
 return 0;
}

/* removerelation: 
 * input: relationtype as string
 * return: integer for operation status
 * operation: Remove an existing association type
 * */
int removerelation(char *relationtype)
{
 /* OPERATION
  * int relationid=getrelationid(relationtype)
  * Query : Check if any entries with relationid in Tagassociation Table exist
  * prompt user to deal with existing entries if any
  * Query : remove entry for relationid in AssociationRelations Table
  * */
 return 0;
}

/* getrelationid: 
 * input: relationtype as string
 * return: relationid as integer
 * operation: Returns relationid for given relationtype
 * */
int getrelationid(char *relationtype)
{
 /* OPERATION
  * Query : return relationid from AssociationRelation Table	
  * */
 return 0;
}

/* getrelationtype: 
 * input: relationid as integer
 * return: relationtype as string
 * operation: Returns relationtype for given relationid
 * */
char *getrelationtype(int relationid)
{
 /* OPERATION
  * Query : return relationtype from AssociationRelation Table
  * */
 return 0;
}

/* --------------------- Others --------------------- */

/* listtags: 
 * input: void
 * return: tagname string. NULL if no tag found
 * operation: List all tags in the system
 * */
char *listtags(void)
{
 /* OPERATION
  * Query : get all tagname from TagDetails Table
  * */
 return 0;
}

/* -------------------- Hashing --------------------- */

/* sethashfile:
 * input: abspath (Absolute Path). It is the path of the file in base file system on which fuse is mounted.
 * return: f_hashkey 
 * operation: Generate hash_key for new file to be added in kwest
 * */
int sethashfile(char *abspath)
{
 /* OPERATION
  * Query : check if file exists in  FileDetails Table
  * Hash Function to generate new f_hashkey
  * return f_hashkey
  * */
 return 0;
}

/* sethashtag:
 * input: tag name string 
 * return: t_hashkey 
 * operation: Generate hash_key for a new tag to be created in kwest
 * */
int sethashtag(char *tagname)
{
 /* OPERATION
  * Query : check if tag exists in  TagDetails Table
  * Hash Function to generate new t_hashkey
  * return t_hashkey
  * */
 return 0;
}

/* gethashfilekey:
 * input: path as string. path can be a filename or a hierarchy of tags it is associated with in kwest.
 * return: f_hashkey 
 * operation: Hash_key for file in kwest
 * */
int gethashfilekey(char *path)
{
 /* OPERATION
  * Decode list of tags and filename from path
  * Query : get f_hashkey from tags & filename	from FileAssociation Table
  * */
 return 0;
}

/* gethashtagkey:
 * input: tag name string 
 * return: t_hashkey 
 * operation: Hash_key for a tag in kwest
 * */
int gethashtagkey(char *tagname)
{
 /* OPERATION
  * Query : get t_hashkey from TagDetails table
  * */
 return 0;
}

/* gethashfile:
 * input: hash_key of file 
 * return: filename string 
 * operation: Retrieve filename by its hash_key
 * */
char *gethashfile(int f_hashkey)
{
 /* OPERATION
  * Query : Return f_name from FileDetails Table
  * */
 return 0;
}

/* gethashtag:
 * input: hash_key of tag 
 * return: tag name string 
 * operation: Retrieve tag name by its hash_key
 * */
char *gethashtag(int t_hashkey)
{
 /* OPERATION
  * Query : Return tagname from TagDetails Table
  * */
 return 0;
}
